### ISSUE TITLE
Long-polling causes LigHTTPd/FastCGI to stop responding

### ISSUE THREAD

**Issue by aarontc** [cdhowie/Bitcoin-mining-proxy#12]
I'm still tracking down the exact cause, but if long-polling is enabled and you serve the proxy with LigHTTPd, it will quit responding to requests as the PHP FastCGI process hangs indefinitely.

Increasing the "max-procs" directive will delay this but it eventually happens in every configuration I've tried.

If you want more details, let me know, otherwise I'll keep pursuing this on my own and see if I can find a way to fix it.

**Comment by elitak** [comment]
I get this too. I hadn't considered it was because of Long-Polling, but I guess that makes more sense.

**Comment by aarontc** [comment]
I've experienced the same problem with Apache2 using mod_php5... further investigation set for this weekend.
