### ISSUE TITLE
UFAsoft miner share submissions failing

### ISSUE THREAD

**Issue by pokeie** [cdhowie/Bitcoin-mining-proxy#16]
It would seem that the ufasoft miner is failing to communicate with the proxy correctly. It receives work from the proxy, but when it submits completed  work, it never is actually processed, or passed through to the pool by the proxy. I have tried monitoring packets to see what is different about how ufa communicated vs puddinpop rpc, but apparently this is above my pay grade to figure out and contribute a solution.

**Comment by KnightAR** [comment]
I've gotten a bit farther tracking down the problem but I still haven't fully understood why, When work is submitted it errors out with "Work not found in proxy database." and I also checked the database for the result and it really doesn't exist, but there are entries in the database for the miner ... it just doesn't include the data its sending. Here's an output from the json_error function:

`O:8:"stdClass":3:{s:5:"error";s:33:"Work not found in proxy database.";s:6:"result";N;s:2:"id";s:7:"jsonrpc";}`

**Comment by wyze** [comment]
Haha, sorry guys, still trying to get the hang of git. Basically, what causes this failing is that the return data from Ufasoft miner comes back as all uppercase in the hash string. The hash is stored in the database with a ascii_bin collation which makes it case sensitive. This is my work around which allows the shares to get submitted and shown up correctly on the dashboard.

**Comment by cdhowie** [comment]
Thanks for the patch, wyze.  To be a bit more complete with the fix, I'm converting to lowercase when the data is initially inserted as well.  This would only be a problem if the pool/bitcoind returned the data uppercase, but you never know... it's good to cover all your bases.  (It's the old "be strict with your output and liberal with your input" bit of wisdom.)

**Comment by pokeie** [comment]
yeay! I will convert and test today. The only concern that would exist is if at the pool, if they expect a certain case. But probably not, since they all seem to use the same exact pool software. heh. Thanks guys.

**Comment by cdhowie** [comment]
The pools themselves should accept upper or lowercase.  If they don't, then your miner wouldn't work directly against the pool anyway!  And in that case we could always patch the proxy to convert the data string to lower-case before sending it to the pool.
