### ISSUE TITLE
Copy worker/pool configuration.

### ISSUE THREAD

**Issue by wyze** [cdhowie/Bitcoin-mining-proxy#19]
Reference this post here: http://forum.bitcoin.org/index.php?topic=5506.msg219633#msg219633

Don't know if this would be really usable. I can see if you want multiple workers on the proxy to point to one worker on the pool. Does that defeat the point of this proxy?

**Comment by elitak** [comment]
If you want to setup many workers in a batch operation, that can be done in SQL. The schema is very simple.

I may be wrong, but I think that having N slaves proxied to 1 upstream mining pool could result in duplicated work. I don't believe bitcoin-mining-proxy partitions the work across multiple slave accounts. I'm not ever sure if that's feasible, but I'm not familiar enough with the pooling protocol to say for certain.

**Comment by edgeman16** [comment]
I wrote a small PHP cli script to toggle pools on/off, or rather promote certain pools to highest priority or lowest priority.
Wasn't difficult.

As for the multiple workers thing, some pools only have one "worker" defined (I'm thinking of ones like Eligius, where the username is your bitcoin address and the password is blank/not used; in these cases all miners are using the same username/password).
