### ISSUE TITLE
Extra \r\n\r\n sent after JSON content

### ISSUE THREAD

**Issue by luke-jr** [cdhowie/Bitcoin-mining-proxy#44]
The proxy is sending an extra "\r\n\r\n" after the JSON content of the HTTP request. This is an error.

**Comment by cdhowie** [comment]
Whitespace is insignificant most places in JSON.  Please cite which part of the JSON-RPC specification indicates that trailing whitespace is forbidden.

**Comment by cdhowie** [comment]
From the [JSON spec](http://www.ietf.org/rfc/rfc4627.txt):

>   These are the six structural characters:
> 
> ```
>  begin-array     = ws %x5B ws  ; [ left square bracket
> 
>  begin-object    = ws %x7B ws  ; { left curly bracket
> 
>  end-array       = ws %x5D ws  ; ] right square bracket
> 
>  end-object      = ws %x7D ws  ; } right curly bracket
> 
>  name-separator  = ws %x3A ws  ; : colon
> 
>  value-separator = ws %x2C ws  ; , comma
> ```
> 
>   Insignificant whitespace is allowed before or after any of the six
>   structural characters.
> 
> ```
>  ws = *(
>            %x20 /              ; Space
>            %x09 /              ; Horizontal tab
>            %x0A /              ; Line feed or New line
>            %x0D                ; Carriage return
>        )
> ```

**Comment by luke-jr** [comment]
It's not counted in Content-Length

**Comment by cdhowie** [comment]
Are you saying that the Content-Length header includes the 4 whitespace bytes and shouldn't, or that it doesn't include them and it should?

**Comment by luke-jr** [comment]
The Content-Length header only counts the bytes up to the '}' and does not include the \r\n\r\n following it. It should.

**Comment by cdhowie** [comment]
The proxy does not directly set the Content-Length header.  This would be a bug or misconfiguration in the server stack (PHP and/or your httpd).
