### ISSUE TITLE
Add timezone option to configuration for display

### ISSUE THREAD

**Issue by cdhowie** [cdhowie/Bitcoin-mining-proxy#7]
`config.inc.php` should have an option for the timezone (either GMT offset or proper named zone) that will be used to adjust timestamps before they are displayed.

**Comment by edgeman16** [comment]
I would also like to vote for this issue, as I'm not used to UTC and it takes me a few seconds to determine when exactly events have been happening.

**Comment by cdhowie** [comment]
Implemented in commit b51a2927b54b64929a39.

**Comment by edgeman16** [comment]
Very much appreciated :)
