### ISSUE TITLE
Allow disabling of long polling by miner or pool

### ISSUE THREAD

**Issue by tecnobrat** [cdhowie/Bitcoin-mining-proxy#9]
There are some clients which don't support long polling using params (phoenix is one), and end up hammering the webserver over and over.

Also long polling uses up a php process indefinitely.  I have had a situation where a client keeps hitting that URL every 5 seconds (because its having some sort of issues), causing all of the backend PHP processes to be used up.

Until this is a little more stable, I've manually edited the code to not use long polling at all.

**Comment by cdhowie** [comment]
On 06/02/2011 04:58 PM, tecnobrat wrote:

> There are some clients which don't support long polling using params 
> (phoenix is one), and end up hammering the webserver over and over.

I plan on adding a workaround for Phoenix at some point.

> Also long polling uses up a php process indefinitely. I have had a 
> situation where a client keeps hitting that URL every 5 seconds
> (because its having some sort of issues), causing all of the backend
> PHP processes to be used up.

The latest code shouldn't have this problem anymore, as the maximum time
a long-polling request can last is just over an hour.  Long-polling
requests used to time out after a day, so you'd see those processes last
a day before being recycled.

## 

Chris Howie
http://www.chrishowie.com
http://en.wikipedia.org/wiki/User:Crazycomputers

If you correspond with me on a regular basis, please read this document:
http://www.chrishowie.com/email-preferences/

PGP fingerprint: 2B7A B280 8B12 21CC 260A DF65 6FCE 505A CF83 38F5

---

```
                IMPORTANT INFORMATION/DISCLAIMER
```

This document should be read only by those persons to whom it is
addressed.  If you have received this message it was obviously addressed
to you and therefore you can read it.

Additionally, by sending an email to ANY of my addresses or to ANY
mailing lists to which I am subscribed, whether intentionally or
accidentally, you are agreeing that I am "the intended recipient," and
that I may do whatever I wish with the contents of any message received
from you, unless a pre-existing agreement prohibits me from so doing.

This overrides any disclaimer or statement of confidentiality that may
be included on your message.

**Comment by tecnobrat** [comment]
I think the issue for me is that I use nginx, which has a maximum execute timeout by default for fastcgi scripts (60 seconds by default), and these threads were being terminated by the webserver.

Are you referring to this code?

``` php
        $context_options = array(
            'method'    => 'GET',
            'header'    => $authHeader,
            'timeout'   => 3900
        );

```

I tried tweaking this to 30 seconds, didn't seem to have an affect.

**Comment by cdhowie** [comment]
On 06/02/2011 06:02 PM, tecnobrat wrote:

> I think the issue for me is that I use nginx, which has a maximum 
> execute timeout by default for fastcgi scripts (60 seconds by
> default), and these threads were being terminated by the webserver.

Try setting this to two hours.

## 

Chris Howie
http://www.chrishowie.com
http://en.wikipedia.org/wiki/User:Crazycomputers

If you correspond with me on a regular basis, please read this document:
http://www.chrishowie.com/email-preferences/

PGP fingerprint: 2B7A B280 8B12 21CC 260A DF65 6FCE 505A CF83 38F5

---

```
                IMPORTANT INFORMATION/DISCLAIMER
```

This document should be read only by those persons to whom it is
addressed.  If you have received this message it was obviously addressed
to you and therefore you can read it.

Additionally, by sending an email to ANY of my addresses or to ANY
mailing lists to which I am subscribed, whether intentionally or
accidentally, you are agreeing that I am "the intended recipient," and
that I may do whatever I wish with the contents of any message received
from you, unless a pre-existing agreement prohibits me from so doing.

This overrides any disclaimer or statement of confidentiality that may
be included on your message.

**Comment by cdhowie** [comment]
The Phoenix issue should be resolved at this point (I implemented the workaround a few weeks ago).  Are there any more problems you're experiencing related to long-polling?

**Comment by cdhowie** [comment]
OP has not responded to inquiry; assuming the matter is resolved.

Also, commit e166598 allows long polling to be disabled completely if this is desired.
